site_name: Imgur.API
pages:
- 'Introduction': 'index.md'
- 'Status': 'status.md'
- 'Quick Start': 'quick-start.md'
- 'Authentication': 'authentication.md'
- 'OAuth2': 'oauth2.md'
- 'Endpoints':
    - 'Image Endpoint': 'endpoints/image-endpoint.md'
- 'FAQ': 'faq.md'