site_name: Imgur.API
pages:
- 'Introduction': 'index.md'
- 'Quick Start': 'quick-start.md'
- 'Authentication': 'authentication.md'
- 'OAuth2': 'oauth2.md'
- 'Endpoints':
    - 'Account Endpoint': 'account-endpoint.md'
    - 'Album Endpoint': 'album-endpoint.md'
    - 'Comment Endpoint': 'comment-endpoint.md'
    - 'Conversation Endpoint': 'conversation-endpoint.md'
    - 'Custom Gallery Endpoint': 'custom-gallery-endpoint.md'
    - 'Gallery Endpoint': 'gallery-endpoint.md'
    - 'Image Endpoint': 'image-endpoint.md'
    - 'MemeGen Endpoint': 'memegen-endpoint.md'
    - 'Notification Endpoint': 'notification-endpoint.md'
    - 'OAuth2 Endpoint': 'oauth2-endpoint.md'
    - 'Rate Limit Endpoint': 'rate-limit-endpoint.md'
    - 'Topic Endpoint': 'topic-endpoint.md'
- 'Status': 'status.md'
- 'Release Notes': 'release-notes.md'
- 'FAQ': 'faq.md'