site_name: Imgur.API
pages:
- 'Introduction': 'index.md'
- 'Quick Start': 'quick-start.md'
- 'Authentication': 'authentication.md'
- 'OAuth2': 'oauth2.md'
- 'Endpoints':
    - 'Account Endpoint': 'account-endpoint.md'
    - 'Album Endpoint': 'album-endpoint.md'
    - 'Image Endpoint': 'image-endpoint.md'
    - 'OAuth2 Endpoint': 'oauth2-endpoint.md'
	- 'Rate Limit Endpoint': 'rate-limit-endpoint.md'
- 'Status': 'status.md'
- 'Release Notes': 'release-notes.md'
- 'FAQ': 'faq.md'