// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Major Code Smell", "S107:Methods should not have too many parameters", Justification = "<Pending>", Scope = "member", Target = "~M:Imgur.API.Endpoints.IAlbumEndpoint.UpdateAlbumAsync(System.String,System.String,System.String,System.String,System.String,System.String,System.Collections.Generic.IEnumerable{System.String},System.Collections.Generic.IEnumerable{System.String},System.Threading.CancellationToken)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: SuppressMessage("Major Code Smell", "S107:Methods should not have too many parameters", Justification = "<Pending>", Scope = "member", Target = "~M:Imgur.API.RequestBuilders.ImageRequestBuilder.UploadVideoStreamRequest(System.String,System.IO.Stream,System.String,System.String,System.String,System.String,System.IProgress{System.Int32},System.Nullable{System.Int32})~System.Net.Http.HttpRequestMessage")]
[assembly: SuppressMessage("Major Code Smell", "S107:Methods should not have too many parameters", Justification = "<Pending>", Scope = "member", Target = "~M:Imgur.API.Endpoints.IAlbumEndpoint.CreateAlbumAsync(System.String,System.String,System.String,System.String,System.String,System.Collections.Generic.IEnumerable{System.String},System.Collections.Generic.IEnumerable{System.String},System.Threading.CancellationToken)~System.Threading.Tasks.Task{Imgur.API.Models.IAlbum}")]
[assembly: SuppressMessage("Major Code Smell", "S107:Methods should not have too many parameters", Justification = "<Pending>", Scope = "member", Target = "~M:Imgur.API.Endpoints.IImageEndpoint.UploadImageAsync(System.IO.Stream,System.String,System.String,System.String,System.String,System.IProgress{System.Int32},System.Nullable{System.Int32},System.Threading.CancellationToken)~System.Threading.Tasks.Task{Imgur.API.Models.IImage}")]
[assembly: SuppressMessage("Major Code Smell", "S107:Methods should not have too many parameters", Justification = "<Pending>", Scope = "member", Target = "~M:Imgur.API.Endpoints.IImageEndpoint.UploadVideoAsync(System.IO.Stream,System.String,System.String,System.String,System.String,System.String,System.Boolean,System.IProgress{System.Int32},System.Nullable{System.Int32},System.Threading.CancellationToken)~System.Threading.Tasks.Task{Imgur.API.Models.IImage}")]
[assembly: SuppressMessage("Major Code Smell", "S107:Methods should not have too many parameters", Justification = "<Pending>", Scope = "member", Target = "~M:Imgur.API.Endpoints.ImageEndpoint.UploadImageInternalAsync(System.IO.Stream,System.String,System.String,System.String,System.String,System.IProgress{System.Int32},System.Nullable{System.Int32},System.Threading.CancellationToken)~System.Threading.Tasks.Task{Imgur.API.Models.IImage}")]
[assembly: SuppressMessage("Major Code Smell", "S107:Methods should not have too many parameters", Justification = "<Pending>", Scope = "member", Target = "~M:Imgur.API.Endpoints.ImageEndpoint.UploadVideoInternalAsync(System.IO.Stream,System.String,System.String,System.String,System.String,System.IProgress{System.Int32},System.Nullable{System.Int32},System.Threading.CancellationToken)~System.Threading.Tasks.Task{Imgur.API.Models.IImage}")]
[assembly: SuppressMessage("Major Code Smell", "S107:Methods should not have too many parameters", Justification = "<Pending>", Scope = "member", Target = "~M:Imgur.API.RequestBuilders.ImageRequestBuilder.UploadImageStreamRequest(System.String,System.IO.Stream,System.String,System.String,System.String,System.String,System.IProgress{System.Int32},System.Nullable{System.Int32})~System.Net.Http.HttpRequestMessage")]
[assembly: SuppressMessage("Minor Code Smell", "S1075:URIs should not be hardcoded", Justification = "<Pending>", Scope = "member", Target = "~F:Imgur.API.Endpoints.OAuth2Endpoint.AuthorizationEndpointUrl")]
[assembly: SuppressMessage("Minor Code Smell", "S1075:URIs should not be hardcoded", Justification = "<Pending>", Scope = "member", Target = "~F:Imgur.API.Endpoints.OAuth2Endpoint.TokenEndpointUrl")]
