using System.Threading;
using System.Threading.Tasks;
using Imgur.API.Models;

namespace Imgur.API.Endpoints
{
    /// <summary>
    /// Authorizes account access.
    /// </summary>
    public interface IOAuth2Endpoint : IEndpoint
    {
        /// <summary>
        /// Creates an authorization url that can be used to authorize access to a user's account.
        /// </summary>
        /// <param name="state">Any state which may be useful to your application upon receipt of the response.</param>
        /// <returns></returns>
        string GetAuthorizationUrl(string state = null);

        /// <summary>
        /// If a user has authorized their account but you no longer have a valid access token for them,
        /// then a new one can be generated by using the refresh token.
        /// </summary>
        /// <param name="refreshToken"></param>
        /// <param name="cancellationToken"></param>
        /// <returns></returns>
        Task<IOAuth2Token> GetTokenAsync(string refreshToken, CancellationToken cancellationToken = default);
    }
}
